/************************************************************\
 **     Copyright (c) 2012-2024 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	E:/projects/2023_10_10_HX4S20_test/spi_FLASH_SDRAM_pic/HX4S20/al_ip/sys_pll.v
 ** Date	:	2025 06 10
 ** TD version	:	5.6.119222
\************************************************************/

///////////////////////////////////////////////////////////////////////////////
//	Input frequency:               50.000000MHz
//	Clock multiplication factor: 2
//	Clock division factor:       1
//	Clock information:
//		Clock name	| Frequency 	| Phase shift
//		C0        	| 100.000000MHZ	| 0.0000  DEG  
//		C1        	| 125.000000MHZ	| 0.0000  DEG  
//		C2        	| 125.000000MHZ	| 180.0000 DEG  
///////////////////////////////////////////////////////////////////////////////
`timescale 1 ns / 100 fs

////////////////////////////////////////////////////////////////////////////////
// 模块: sys_pll  (TD 生成的锁相环 IP, 切勿手工修改内部参数)
// 输入: 板载 50MHz 晶振 (refclk)
// 输出(与顶层时钟域对应):
//   clk0_out = 100MHz             -> 系统 / SD 卡时钟 (sd_card_clk)
//   clk1_out = 125MHz             -> SDRAM 控制器时钟 (ext_mem_clk)
//   clk2_out = 125MHz(相位180°)   -> SDRAM 数据选通(DQS)伴随时钟
// 说明: 频率/相位由 TD IP Generator 配置(FIN=50M, FBCLK_DIV=2, CLKC0_DIV=10,
//       CLKC1_DIV=8, CLKC2_DIV=8 CPHASE=3), 修改请回到 TD 工程重新生成本文件。
////////////////////////////////////////////////////////////////////////////////
module sys_pll (
  refclk,
  reset,
  clk0_out,
  clk1_out,
  clk2_out 
);

  input refclk;
  input reset;
  output clk0_out;
  output clk1_out;
  output clk2_out;

  wire clk0_buf;

  EG_LOGIC_BUFG bufg_feedback (
    .i(clk0_buf),
    .o(clk0_out) 
  );

  EG_PHY_PLL #(
    .DPHASE_SOURCE("DISABLE"),
    .DYNCFG("DISABLE"),
    .FIN("50.000000"),
    .FEEDBK_MODE("NORMAL"),
    .FEEDBK_PATH("CLKC0_EXT"),
    .STDBY_ENABLE("DISABLE"),
    .PLLRST_ENA("ENABLE"),
    .SYNC_ENABLE("DISABLE"),
    .GMC_GAIN(4),
    .ICP_CURRENT(29),
    .KVCO(4),
    .LPF_CAPACITOR(1),
    .LPF_RESISTOR(2),
    .REFCLK_DIV(1),
    .FBCLK_DIV(2),
    .CLKC0_ENABLE("ENABLE"),
    .CLKC0_DIV(10),
    .CLKC0_CPHASE(9),
    .CLKC0_FPHASE(0),
    .CLKC1_ENABLE("ENABLE"),
    .CLKC1_DIV(8),
    .CLKC1_CPHASE(7),
    .CLKC1_FPHASE(0),
    .CLKC2_ENABLE("ENABLE"),
    .CLKC2_DIV(8),
    .CLKC2_CPHASE(3),
    .CLKC2_FPHASE(0) 
  ) pll_inst (
    .refclk(refclk),
    .reset(reset),
    .stdby(1'b0),
    .extlock(open),
    .load_reg(1'b0),
    .psclk(1'b0),
    .psdown(1'b0),
    .psstep(1'b0),
    .psclksel(3'b000),
    .psdone(open),
    .dclk(1'b0),
    .dcs(1'b0),
    .dwe(1'b0),
    .di(8'b00000000),
    .daddr(6'b000000),
    .do({open, open, open, open, open, open, open, open}),
    .fbclk(clk0_out),
    .clkc({open, open, clk2_out, clk1_out, clk0_buf}) 
  );

endmodule

