// Generated by tools/gen_marquee_font.py -- DO NOT EDIT BY HAND.
// Re-run the generator instead; tools/check_marquee_transcription.py
// compares this file against a fresh render, bit for bit.
//
// Included from inside marquee_overlay.v's module body, so this file holds
// a bare function and must NOT be added to the .al file list.
//
// Slogan    : FPGA创新设计竞赛国赛十周年
// Font      : C:/Windows/Fonts/simhei.ttf @ 24 px, threshold 110
// Cells     : 15 x 24 px, pitch 32 px (4 px gutter each side)
// Bit order : bit 23 is the leftmost column of the row.
// Blank rows are folded into the default arm to keep the file short.
// The argument is cell_idx, not cell: `cell` is a Verilog-2001 reserved
// word and TD rejects it with HDL-8007.

function [23:0] marquee_glyph;
    input [3:0] cell_idx;
    input [4:0] row;
    begin
        case (cell_idx)
            4'd0: case (row)   // F
                5'd3: marquee_glyph = 24'h01FF80;
                5'd4: marquee_glyph = 24'h01FF80;
                5'd5: marquee_glyph = 24'h01C000;
                5'd6: marquee_glyph = 24'h018000;
                5'd7: marquee_glyph = 24'h018000;
                5'd8: marquee_glyph = 24'h018000;
                5'd9: marquee_glyph = 24'h018000;
                5'd10: marquee_glyph = 24'h01FE00;
                5'd11: marquee_glyph = 24'h01FE00;
                5'd12: marquee_glyph = 24'h01C000;
                5'd13: marquee_glyph = 24'h018000;
                5'd14: marquee_glyph = 24'h018000;
                5'd15: marquee_glyph = 24'h018000;
                5'd16: marquee_glyph = 24'h018000;
                5'd17: marquee_glyph = 24'h018000;
                5'd18: marquee_glyph = 24'h018000;
                5'd19: marquee_glyph = 24'h018000;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd1: case (row)   // P
                5'd3: marquee_glyph = 24'h00F800;
                5'd4: marquee_glyph = 24'h01FE00;
                5'd5: marquee_glyph = 24'h01C700;
                5'd6: marquee_glyph = 24'h018380;
                5'd7: marquee_glyph = 24'h018180;
                5'd8: marquee_glyph = 24'h018180;
                5'd9: marquee_glyph = 24'h018180;
                5'd10: marquee_glyph = 24'h018380;
                5'd11: marquee_glyph = 24'h01FF00;
                5'd12: marquee_glyph = 24'h01FE00;
                5'd13: marquee_glyph = 24'h01C000;
                5'd14: marquee_glyph = 24'h018000;
                5'd15: marquee_glyph = 24'h018000;
                5'd16: marquee_glyph = 24'h018000;
                5'd17: marquee_glyph = 24'h018000;
                5'd18: marquee_glyph = 24'h018000;
                5'd19: marquee_glyph = 24'h008000;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd2: case (row)   // G
                5'd3: marquee_glyph = 24'h001C00;
                5'd4: marquee_glyph = 24'h007E00;
                5'd5: marquee_glyph = 24'h00E700;
                5'd6: marquee_glyph = 24'h00C300;
                5'd7: marquee_glyph = 24'h01C380;
                5'd8: marquee_glyph = 24'h018180;
                5'd9: marquee_glyph = 24'h018000;
                5'd10: marquee_glyph = 24'h018000;
                5'd11: marquee_glyph = 24'h018F00;
                5'd12: marquee_glyph = 24'h018F80;
                5'd13: marquee_glyph = 24'h018180;
                5'd14: marquee_glyph = 24'h018180;
                5'd15: marquee_glyph = 24'h01C180;
                5'd16: marquee_glyph = 24'h00C380;
                5'd17: marquee_glyph = 24'h00E780;
                5'd18: marquee_glyph = 24'h007F80;
                5'd19: marquee_glyph = 24'h003980;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd3: case (row)   // A
                5'd3: marquee_glyph = 24'h001800;
                5'd4: marquee_glyph = 24'h001800;
                5'd5: marquee_glyph = 24'h003C00;
                5'd6: marquee_glyph = 24'h003C00;
                5'd7: marquee_glyph = 24'h003C00;
                5'd8: marquee_glyph = 24'h007C00;
                5'd9: marquee_glyph = 24'h006600;
                5'd10: marquee_glyph = 24'h006600;
                5'd11: marquee_glyph = 24'h006600;
                5'd12: marquee_glyph = 24'h00E700;
                5'd13: marquee_glyph = 24'h00FF00;
                5'd14: marquee_glyph = 24'h00FF00;
                5'd15: marquee_glyph = 24'h01C300;
                5'd16: marquee_glyph = 24'h018380;
                5'd17: marquee_glyph = 24'h018180;
                5'd18: marquee_glyph = 24'h018180;
                5'd19: marquee_glyph = 24'h010080;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd4: case (row)   // 创
                5'd1: marquee_glyph = 24'h010000;
                5'd2: marquee_glyph = 24'h01800C;
                5'd3: marquee_glyph = 24'h038008;
                5'd4: marquee_glyph = 24'h07E008;
                5'd5: marquee_glyph = 24'h067188;
                5'd6: marquee_glyph = 24'h0C3988;
                5'd7: marquee_glyph = 24'h1C1D88;
                5'd8: marquee_glyph = 24'h380988;
                5'd9: marquee_glyph = 24'h7FF188;
                5'd10: marquee_glyph = 24'h2FF188;
                5'd11: marquee_glyph = 24'h0C3188;
                5'd12: marquee_glyph = 24'h0C3188;
                5'd13: marquee_glyph = 24'h0C3188;
                5'd14: marquee_glyph = 24'h0C3188;
                5'd15: marquee_glyph = 24'h0C7188;
                5'd16: marquee_glyph = 24'h0DE188;
                5'd17: marquee_glyph = 24'h0CC188;
                5'd18: marquee_glyph = 24'h0C0008;
                5'd19: marquee_glyph = 24'h0C0C08;
                5'd20: marquee_glyph = 24'h0C1C18;
                5'd21: marquee_glyph = 24'h0FF878;
                5'd22: marquee_glyph = 24'h07F038;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd5: case (row)   // 新
                5'd0: marquee_glyph = 24'h010000;
                5'd1: marquee_glyph = 24'h03007C;
                5'd2: marquee_glyph = 24'h0383FE;
                5'd3: marquee_glyph = 24'h3FFB00;
                5'd4: marquee_glyph = 24'h3FF300;
                5'd5: marquee_glyph = 24'h086300;
                5'd6: marquee_glyph = 24'h086300;
                5'd7: marquee_glyph = 24'h0CC300;
                5'd8: marquee_glyph = 24'h3FFBFE;
                5'd9: marquee_glyph = 24'h7FFBFE;
                5'd10: marquee_glyph = 24'h030318;
                5'd11: marquee_glyph = 24'h030318;
                5'd12: marquee_glyph = 24'h339318;
                5'd13: marquee_glyph = 24'h3FFB18;
                5'd14: marquee_glyph = 24'h030318;
                5'd15: marquee_glyph = 24'h1B0318;
                5'd16: marquee_glyph = 24'h1B6318;
                5'd17: marquee_glyph = 24'h3B3618;
                5'd18: marquee_glyph = 24'h733618;
                5'd19: marquee_glyph = 24'h630618;
                5'd20: marquee_glyph = 24'h0F0C18;
                5'd21: marquee_glyph = 24'h070C18;
                5'd22: marquee_glyph = 24'h000018;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd6: case (row)   // 设
                5'd1: marquee_glyph = 24'h181FC0;
                5'd2: marquee_glyph = 24'h1C3FC0;
                5'd3: marquee_glyph = 24'h0E30C0;
                5'd4: marquee_glyph = 24'h0630C0;
                5'd5: marquee_glyph = 24'h0030C0;
                5'd6: marquee_glyph = 24'h0030C0;
                5'd7: marquee_glyph = 24'h0070E0;
                5'd8: marquee_glyph = 24'h7CE0FC;
                5'd9: marquee_glyph = 24'h7CC07C;
                5'd10: marquee_glyph = 24'h0C4000;
                5'd11: marquee_glyph = 24'h0CFFF0;
                5'd12: marquee_glyph = 24'h0C3070;
                5'd13: marquee_glyph = 24'h0C3060;
                5'd14: marquee_glyph = 24'h0C1860;
                5'd15: marquee_glyph = 24'h0C1CC0;
                5'd16: marquee_glyph = 24'h0D8DC0;
                5'd17: marquee_glyph = 24'h0F8780;
                5'd18: marquee_glyph = 24'h0F0780;
                5'd19: marquee_glyph = 24'h0E1FE0;
                5'd20: marquee_glyph = 24'h0C78FE;
                5'd21: marquee_glyph = 24'h01E01C;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd7: case (row)   // 计
                5'd1: marquee_glyph = 24'h080180;
                5'd2: marquee_glyph = 24'h1C0180;
                5'd3: marquee_glyph = 24'h0E0180;
                5'd4: marquee_glyph = 24'h070180;
                5'd5: marquee_glyph = 24'h030180;
                5'd6: marquee_glyph = 24'h000180;
                5'd7: marquee_glyph = 24'h000180;
                5'd8: marquee_glyph = 24'h7EFFFE;
                5'd9: marquee_glyph = 24'h7EFFFE;
                5'd10: marquee_glyph = 24'h060180;
                5'd11: marquee_glyph = 24'h060180;
                5'd12: marquee_glyph = 24'h060180;
                5'd13: marquee_glyph = 24'h060180;
                5'd14: marquee_glyph = 24'h060180;
                5'd15: marquee_glyph = 24'h06C180;
                5'd16: marquee_glyph = 24'h06C180;
                5'd17: marquee_glyph = 24'h078180;
                5'd18: marquee_glyph = 24'h070180;
                5'd19: marquee_glyph = 24'h0E0180;
                5'd20: marquee_glyph = 24'h040180;
                5'd21: marquee_glyph = 24'h000180;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd8: case (row)   // 竞
                5'd1: marquee_glyph = 24'h001800;
                5'd2: marquee_glyph = 24'h001800;
                5'd3: marquee_glyph = 24'h3FFFF8;
                5'd4: marquee_glyph = 24'h3FFFFC;
                5'd5: marquee_glyph = 24'h010100;
                5'd6: marquee_glyph = 24'h038380;
                5'd7: marquee_glyph = 24'h018300;
                5'd8: marquee_glyph = 24'h7FFFFE;
                5'd9: marquee_glyph = 24'h7FFFFE;
                5'd12: marquee_glyph = 24'h0FFFF0;
                5'd13: marquee_glyph = 24'h0C0030;
                5'd14: marquee_glyph = 24'h0C0030;
                5'd15: marquee_glyph = 24'h0FFFF0;
                5'd16: marquee_glyph = 24'h0FFFF0;
                5'd17: marquee_glyph = 24'h00E600;
                5'd18: marquee_glyph = 24'h00C600;
                5'd19: marquee_glyph = 24'h00C604;
                5'd20: marquee_glyph = 24'h038706;
                5'd21: marquee_glyph = 24'h1F07FC;
                5'd22: marquee_glyph = 24'h3C03FC;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd9: case (row)   // 赛
                5'd1: marquee_glyph = 24'h001000;
                5'd2: marquee_glyph = 24'h003000;
                5'd3: marquee_glyph = 24'h7FFFF8;
                5'd4: marquee_glyph = 24'h700018;
                5'd5: marquee_glyph = 24'h618618;
                5'd6: marquee_glyph = 24'h2FFFD8;
                5'd7: marquee_glyph = 24'h0FFFC0;
                5'd8: marquee_glyph = 24'h018600;
                5'd9: marquee_glyph = 24'h0FFFE0;
                5'd10: marquee_glyph = 24'h018600;
                5'd11: marquee_glyph = 24'h7FFFF8;
                5'd12: marquee_glyph = 24'h7FFFF8;
                5'd13: marquee_glyph = 24'h070300;
                5'd14: marquee_glyph = 24'h1E01C0;
                5'd15: marquee_glyph = 24'h7FFFFC;
                5'd16: marquee_glyph = 24'h67FFB8;
                5'd17: marquee_glyph = 24'h063180;
                5'd18: marquee_glyph = 24'h067180;
                5'd19: marquee_glyph = 24'h066400;
                5'd20: marquee_glyph = 24'h01C700;
                5'd21: marquee_glyph = 24'h1F83C0;
                5'd22: marquee_glyph = 24'h1E00C0;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd10: case (row)   // 国
                5'd1: marquee_glyph = 24'h1FFFF8;
                5'd2: marquee_glyph = 24'h3FFFFC;
                5'd3: marquee_glyph = 24'h30000C;
                5'd4: marquee_glyph = 24'h30000C;
                5'd5: marquee_glyph = 24'h33FFCC;
                5'd6: marquee_glyph = 24'h33FFCC;
                5'd7: marquee_glyph = 24'h30180C;
                5'd8: marquee_glyph = 24'h30180C;
                5'd9: marquee_glyph = 24'h30180C;
                5'd10: marquee_glyph = 24'h33FFCC;
                5'd11: marquee_glyph = 24'h31388C;
                5'd12: marquee_glyph = 24'h30190C;
                5'd13: marquee_glyph = 24'h301B8C;
                5'd14: marquee_glyph = 24'h30190C;
                5'd15: marquee_glyph = 24'h3338CC;
                5'd16: marquee_glyph = 24'h33FFCC;
                5'd17: marquee_glyph = 24'h30000C;
                5'd18: marquee_glyph = 24'h30000C;
                5'd19: marquee_glyph = 24'h38001C;
                5'd20: marquee_glyph = 24'h3FFFFC;
                5'd21: marquee_glyph = 24'h30000C;
                5'd22: marquee_glyph = 24'h100000;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd11: case (row)   // 赛
                5'd1: marquee_glyph = 24'h001000;
                5'd2: marquee_glyph = 24'h003000;
                5'd3: marquee_glyph = 24'h7FFFF8;
                5'd4: marquee_glyph = 24'h700018;
                5'd5: marquee_glyph = 24'h618618;
                5'd6: marquee_glyph = 24'h2FFFD8;
                5'd7: marquee_glyph = 24'h0FFFC0;
                5'd8: marquee_glyph = 24'h018600;
                5'd9: marquee_glyph = 24'h0FFFE0;
                5'd10: marquee_glyph = 24'h018600;
                5'd11: marquee_glyph = 24'h7FFFF8;
                5'd12: marquee_glyph = 24'h7FFFF8;
                5'd13: marquee_glyph = 24'h070300;
                5'd14: marquee_glyph = 24'h1E01C0;
                5'd15: marquee_glyph = 24'h7FFFFC;
                5'd16: marquee_glyph = 24'h67FFB8;
                5'd17: marquee_glyph = 24'h063180;
                5'd18: marquee_glyph = 24'h067180;
                5'd19: marquee_glyph = 24'h066400;
                5'd20: marquee_glyph = 24'h01C700;
                5'd21: marquee_glyph = 24'h1F83C0;
                5'd22: marquee_glyph = 24'h1E00C0;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd12: case (row)   // 十
                5'd1: marquee_glyph = 24'h001800;
                5'd2: marquee_glyph = 24'h001800;
                5'd3: marquee_glyph = 24'h001800;
                5'd4: marquee_glyph = 24'h001800;
                5'd5: marquee_glyph = 24'h001800;
                5'd6: marquee_glyph = 24'h001800;
                5'd7: marquee_glyph = 24'h001800;
                5'd8: marquee_glyph = 24'h001800;
                5'd9: marquee_glyph = 24'h7FFFFE;
                5'd10: marquee_glyph = 24'h7FFFFE;
                5'd11: marquee_glyph = 24'h001800;
                5'd12: marquee_glyph = 24'h001800;
                5'd13: marquee_glyph = 24'h001800;
                5'd14: marquee_glyph = 24'h001800;
                5'd15: marquee_glyph = 24'h001800;
                5'd16: marquee_glyph = 24'h001800;
                5'd17: marquee_glyph = 24'h001800;
                5'd18: marquee_glyph = 24'h001800;
                5'd19: marquee_glyph = 24'h001800;
                5'd20: marquee_glyph = 24'h001800;
                5'd21: marquee_glyph = 24'h001800;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd13: case (row)   // 周
                5'd1: marquee_glyph = 24'h07FFFC;
                5'd2: marquee_glyph = 24'h07FFFC;
                5'd3: marquee_glyph = 24'h06040C;
                5'd4: marquee_glyph = 24'h060C0C;
                5'd5: marquee_glyph = 24'h060C0C;
                5'd6: marquee_glyph = 24'h06FFCC;
                5'd7: marquee_glyph = 24'h060C0C;
                5'd8: marquee_glyph = 24'h060C0C;
                5'd9: marquee_glyph = 24'h06FFEC;
                5'd10: marquee_glyph = 24'h07FFEC;
                5'd11: marquee_glyph = 24'h06000C;
                5'd12: marquee_glyph = 24'h06000C;
                5'd13: marquee_glyph = 24'h047FCC;
                5'd14: marquee_glyph = 24'h0C618C;
                5'd15: marquee_glyph = 24'h0C608C;
                5'd16: marquee_glyph = 24'h0C608C;
                5'd17: marquee_glyph = 24'h0C7FCC;
                5'd18: marquee_glyph = 24'h1C7F8C;
                5'd19: marquee_glyph = 24'h18000C;
                5'd20: marquee_glyph = 24'h38007C;
                5'd21: marquee_glyph = 24'h100078;
                default: marquee_glyph = 24'h000000;
            endcase
            4'd14: case (row)   // 年
                5'd1: marquee_glyph = 24'h010000;
                5'd2: marquee_glyph = 24'h018000;
                5'd3: marquee_glyph = 24'h038000;
                5'd4: marquee_glyph = 24'h030000;
                5'd5: marquee_glyph = 24'h07FFFC;
                5'd6: marquee_glyph = 24'h0E0C00;
                5'd7: marquee_glyph = 24'h1C0C00;
                5'd8: marquee_glyph = 24'h1C0C00;
                5'd9: marquee_glyph = 24'h380C00;
                5'd10: marquee_glyph = 24'h37FFF8;
                5'd11: marquee_glyph = 24'h07FFF0;
                5'd12: marquee_glyph = 24'h060C00;
                5'd13: marquee_glyph = 24'h060C00;
                5'd14: marquee_glyph = 24'h060C00;
                5'd15: marquee_glyph = 24'h060C00;
                5'd16: marquee_glyph = 24'h7FFFFE;
                5'd17: marquee_glyph = 24'h000E00;
                5'd18: marquee_glyph = 24'h000C00;
                5'd19: marquee_glyph = 24'h000C00;
                5'd20: marquee_glyph = 24'h000C00;
                5'd21: marquee_glyph = 24'h000C00;
                5'd22: marquee_glyph = 24'h000C00;
                default: marquee_glyph = 24'h000000;
            endcase
            default: marquee_glyph = 24'h000000;
        endcase
    end
endfunction
