// ---------------------------------------------------------------
// Generated by tools/gen_biquad_coeffs.py -- do not edit by hand.
//
// 16-band log-spaced RBJ constant-0dB-peak bandpass bank,
// 100 Hz .. 7000 Hz, Q = 4.0, internal sample rate 24000 Hz.
// Coefficients are signed Q1.16 in 18 bits.
//
// Difference equation, with b1 == 0 and b2 == -b0 exactly:
//   y[n] = B0*(x[n] - x[n-2]) + NA1*y[n-1] + NA2*y[n-2]
// so (x[n] - x[n-2]) is computed once and shared by all bands.
// ---------------------------------------------------------------

localparam COEFF_W = 18;
localparam COEFF_FRAC = 16;

// band_b0: numerator, applied to x[n] - x[n-2]
function signed [COEFF_W-1:0] band_b0;
    input [3:0] idx;
    begin
        case (idx)
            4'd0 : band_b0 = 18'sd214;        //   100.0 Hz
            4'd1 : band_b0 = 18'sd283;        //   132.7 Hz
            4'd2 : band_b0 = 18'sd376;        //   176.2 Hz
            4'd3 : band_b0 = 18'sd498;        //   233.9 Hz
            4'd4 : band_b0 = 18'sd658;        //   310.5 Hz
            4'd5 : band_b0 = 18'sd870;        //   412.1 Hz
            4'd6 : band_b0 = 18'sd1149;       //   547.1 Hz
            4'd7 : band_b0 = 18'sd1512;       //   726.2 Hz
            4'd8 : band_b0 = 18'sd1984;       //   963.9 Hz
            4'd9 : band_b0 = 18'sd2587;       //  1279.6 Hz
            4'd10: band_b0 = 18'sd3344;       //  1698.5 Hz
            4'd11: band_b0 = 18'sd4263;       //  2254.6 Hz
            4'd12: band_b0 = 18'sd5313;       //  2992.8 Hz
            4'd13: band_b0 = 18'sd6377;       //  3972.7 Hz
            4'd14: band_b0 = 18'sd7165;       //  5273.4 Hz
            4'd15: band_b0 = 18'sd7060;       //  7000.0 Hz
            default: band_b0 = 18'sd0;
        endcase
    end
endfunction

// band_na1: -a1, applied to y[n-1]
function signed [COEFF_W-1:0] band_na1;
    input [3:0] idx;
    begin
        case (idx)
            4'd0 : band_na1 = 18'sd130600;     //   100.0 Hz
            4'd1 : band_na1 = 18'sd130426;     //   132.7 Hz
            4'd2 : band_na1 = 18'sd130182;     //   176.2 Hz
            4'd3 : band_na1 = 18'sd129833;     //   233.9 Hz
            4'd4 : band_na1 = 18'sd129327;     //   310.5 Hz
            4'd5 : band_na1 = 18'sd128579;     //   412.1 Hz
            4'd6 : band_na1 = 18'sd127456;     //   547.1 Hz
            4'd7 : band_na1 = 18'sd125740;     //   726.2 Hz
            4'd8 : band_na1 = 18'sd123079;     //   963.9 Hz
            4'd9 : band_na1 = 18'sd118900;     //  1279.6 Hz
            4'd10: band_na1 = 18'sd112288;     //  1698.5 Hz
            4'd11: band_na1 = 18'sd101811;     //  2254.6 Hz
            4'd12: band_na1 = 18'sd85328;      //  2992.8 Hz
            4'd13: band_na1 = 18'sd59890;      //  3972.7 Hz
            4'd14: band_na1 = 18'sd22073;      //  5273.4 Hz
            4'd15: band_na1 = -18'sd30269;     //  7000.0 Hz
            default: band_na1 = 18'sd0;
        endcase
    end
endfunction

// band_na2: -a2, applied to y[n-2]
function signed [COEFF_W-1:0] band_na2;
    input [3:0] idx;
    begin
        case (idx)
            4'd0 : band_na2 = -18'sd65109;     //   100.0 Hz
            4'd1 : band_na2 = -18'sd64969;     //   132.7 Hz
            4'd2 : band_na2 = -18'sd64785;     //   176.2 Hz
            4'd3 : band_na2 = -18'sd64541;     //   233.9 Hz
            4'd4 : band_na2 = -18'sd64219;     //   310.5 Hz
            4'd5 : band_na2 = -18'sd63795;     //   412.1 Hz
            4'd6 : band_na2 = -18'sd63238;     //   547.1 Hz
            4'd7 : band_na2 = -18'sd62511;     //   726.2 Hz
            4'd8 : band_na2 = -18'sd61569;     //   963.9 Hz
            4'd9 : band_na2 = -18'sd60362;     //  1279.6 Hz
            4'd10: band_na2 = -18'sd58848;     //  1698.5 Hz
            4'd11: band_na2 = -18'sd57010;     //  2254.6 Hz
            4'd12: band_na2 = -18'sd54910;     //  2992.8 Hz
            4'd13: band_na2 = -18'sd52781;     //  3972.7 Hz
            4'd14: band_na2 = -18'sd51206;     //  5273.4 Hz
            4'd15: band_na2 = -18'sd51415;     //  7000.0 Hz
            default: band_na2 = 18'sd0;
        endcase
    end
endfunction

